import type { SessionAnalytics } from "./types";

export const DEFAULT_SESSION_ANALYTICS: SessionAnalytics = {
  peak_accepted_error: 0,
  peak_accepted_error_tick: 0,
  mean_accepted_error: 0,
  p95_accepted_error: 0,
  oracle_threshold: 0,
  gate_precision: 0,
  gate_recall: 0,
  false_accept_count: 0,
  false_accept_threshold: 0,
  longest_false_accept_streak: 0,
  mean_false_accept_duration: 0,
  peak_error_during_false_accept: 0,
  false_accept_nearest_gate_r90: 0,
  false_accept_nearest_gate_residual: 0,
  false_accept_nearest_gate_centroid_jump: 0,
  false_reject_count: 0,
  false_reject_threshold: 0,
  r90_reject_count: 0,
  residual_reject_count: 0,
  centroid_jump_reject_count: 0,
  passability_reject_count: 0,
  r90_false_reject_count: 0,
  residual_false_reject_count: 0,
  centroid_jump_false_reject_count: 0,
  passability_false_reject_count: 0,
  gate_availability: 0,
  longest_rejection_streak: 0,
  cold_start_convergence_ticks: 0,
  cold_start_convergence_error: 0,
  worst_reacquisition_ticks: 0,
  mean_reacquisition_ticks: 0,
  reacquisition_count: 0,
  post_convergence_error_stddev: 0,
  peak_r90_at_acceptance: 0,
  neff_collapse_count: 0,
  sensor_dropout_rate: 0,
  total_ticks: 0,
};

function num(v: unknown, fallback = 0): number {
  return typeof v === "number" && Number.isFinite(v) ? v : fallback;
}

/** Coerce replay metadata `analytics` object into `SessionAnalytics`. */
export function parseSessionAnalytics(raw: unknown): SessionAnalytics | null {
  if (!raw || typeof raw !== "object") return null;
  const o = raw as Record<string, unknown>;
  return {
    ...DEFAULT_SESSION_ANALYTICS,
    peak_accepted_error: num(o.peak_accepted_error),
    peak_accepted_error_tick: num(o.peak_accepted_error_tick),
    mean_accepted_error: num(o.mean_accepted_error),
    p95_accepted_error: num(o.p95_accepted_error),
    oracle_threshold: num(o.oracle_threshold),
    gate_precision: num(o.gate_precision),
    gate_recall: num(o.gate_recall),
    false_accept_count: num(o.false_accept_count),
    false_accept_threshold: num(o.false_accept_threshold),
    longest_false_accept_streak: num(o.longest_false_accept_streak),
    mean_false_accept_duration: num(o.mean_false_accept_duration),
    peak_error_during_false_accept: num(o.peak_error_during_false_accept),
    false_accept_nearest_gate_r90: num(o.false_accept_nearest_gate_r90),
    false_accept_nearest_gate_residual: num(o.false_accept_nearest_gate_residual),
    false_accept_nearest_gate_centroid_jump: num(o.false_accept_nearest_gate_centroid_jump),
    false_reject_count: num(o.false_reject_count),
    false_reject_threshold: num(o.false_reject_threshold),
    r90_reject_count: num(o.r90_reject_count),
    residual_reject_count: num(o.residual_reject_count),
    centroid_jump_reject_count: num(o.centroid_jump_reject_count),
    passability_reject_count: num(o.passability_reject_count),
    r90_false_reject_count: num(o.r90_false_reject_count),
    residual_false_reject_count: num(o.residual_false_reject_count),
    centroid_jump_false_reject_count: num(o.centroid_jump_false_reject_count),
    passability_false_reject_count: num(o.passability_false_reject_count),
    gate_availability: num(o.gate_availability),
    longest_rejection_streak: num(o.longest_rejection_streak),
    cold_start_convergence_ticks: num(o.cold_start_convergence_ticks),
    cold_start_convergence_error: num(o.cold_start_convergence_error),
    worst_reacquisition_ticks: num(o.worst_reacquisition_ticks),
    mean_reacquisition_ticks: num(o.mean_reacquisition_ticks),
    reacquisition_count: num(o.reacquisition_count),
    post_convergence_error_stddev: num(o.post_convergence_error_stddev),
    peak_r90_at_acceptance: num(o.peak_r90_at_acceptance),
    neff_collapse_count: num(o.neff_collapse_count),
    sensor_dropout_rate: num(o.sensor_dropout_rate),
    total_ticks: num(o.total_ticks),
  };
}
